"""
Validation domain models.

These are pure Python dataclasses — NOT ORM models.
They carry data between validation components and become the contract
between the Validation Engine and the downstream Cleaning Engine.

Design hierarchy:
  RuleViolation      — one failure on one record for one rule
  ColumnProfile      — statistical summary of a single column
  ValidationReport   — complete per-dataset validation output
  QualityScore       — overall scoring with letter grade
  ValidationResult   — the top-level object returned to the pipeline engine

The Cleaning Engine receives ValidationResult and reads:
  - valid_df        : records that passed all ERROR-severity rules
  - rejected_df     : records that failed at least one ERROR-severity rule
  - report          : full report for audit trail
  - quality_score   : decides whether to proceed or abort
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any

import pandas as pd


# ---------------------------------------------------------------------------
# Severity constants  (mirrors RuleSeverity enum in constants.py)
# ---------------------------------------------------------------------------

class Severity:
    ERROR   = "error"    # record is rejected; pipeline may halt if threshold breached
    WARNING = "warning"  # record is flagged but not rejected
    INFO    = "info"     # informational; never affects record fate


# ---------------------------------------------------------------------------
# RuleViolation — one failure instance
# ---------------------------------------------------------------------------

@dataclass
class RuleViolation:
    """
    A single rule failure on a single record or column.

    One violation is produced per (row, rule) pair that fails.
    The violation carries enough context for the Cleaning Engine to
    decide what action to take and for audit reports to be fully descriptive.
    """

    rule_code: str
    rule_category: str           # schema | dtype | missing | duplicate | business | format | statistical | categorical | referential
    severity: str                # Severity constant
    field_name: str | None       # None for row-level or dataset-level rules
    row_index: int | None        # None for column-level or dataset-level rules
    actual_value: Any            # The offending value (may be None)
    expected: str                # Human-readable expectation description
    message: str                 # Full human-readable failure message
    suggested_fix: str           # Actionable suggestion for the Cleaning Engine
    rule_description: str = ""   # Full rule description from config

    def to_dict(self) -> dict[str, Any]:
        return {
            "rule_code":        self.rule_code,
            "rule_category":    self.rule_category,
            "severity":         self.severity,
            "field_name":       self.field_name,
            "row_index":        self.row_index,
            "actual_value":     str(self.actual_value) if self.actual_value is not None else None,
            "expected":         self.expected,
            "message":          self.message,
            "suggested_fix":    self.suggested_fix,
            "rule_description": self.rule_description,
        }


# ---------------------------------------------------------------------------
# ColumnProfile — statistical snapshot of one column
# ---------------------------------------------------------------------------

@dataclass
class ColumnProfile:
    """
    Statistical and structural profile of a single DataFrame column.

    Generated by StatisticalValidator and used in the ValidationReport.
    """

    column_name: str
    dtype_detected: str           # pandas dtype string
    total_count: int
    null_count: int
    non_null_count: int
    null_pct: float
    unique_count: int
    duplicate_count: int

    # Numeric statistics (None for non-numeric columns)
    min_value: float | None = None
    max_value: float | None = None
    mean: float | None = None
    median: float | None = None
    std_dev: float | None = None
    q1: float | None = None
    q3: float | None = None
    iqr: float | None = None
    skewness: float | None = None
    outlier_count: int = 0

    # Categorical statistics
    top_values: list[tuple[str, int]] = field(default_factory=list)  # [(value, count), …]
    rare_value_count: int = 0    # values appearing < 1% of the time

    # Format issues
    has_leading_whitespace: bool = False
    has_trailing_whitespace: bool = False
    has_mixed_case: bool = False
    empty_string_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "column_name":          self.column_name,
            "dtype_detected":       self.dtype_detected,
            "total_count":          self.total_count,
            "null_count":           self.null_count,
            "null_pct":             round(self.null_pct, 4),
            "unique_count":         self.unique_count,
            "duplicate_count":      self.duplicate_count,
            "min_value":            self.min_value,
            "max_value":            self.max_value,
            "mean":                 self.mean,
            "median":               self.median,
            "std_dev":              self.std_dev,
            "outlier_count":        self.outlier_count,
            "skewness":             self.skewness,
            "has_whitespace_issues": self.has_leading_whitespace or self.has_trailing_whitespace,
            "empty_string_count":   self.empty_string_count,
        }


# ---------------------------------------------------------------------------
# QualityScore — scoring model with letter grade
# ---------------------------------------------------------------------------

@dataclass
class QualityScore:
    """
    Enterprise data quality score with dimensional breakdown.

    Six quality dimensions are scored independently (0–100) and combined
    into an overall score. The overall score maps to a letter grade used
    in executive reports.

    Dimensions:
      completeness  — how few nulls/empty values are present
      validity      — what fraction of records pass all rules
      consistency   — format and value consistency across the dataset
      uniqueness    — absence of duplicates
      integrity     — referential integrity (FK compliance)
      timeliness    — date fields within expected ranges
    """

    # Dimensional scores (0.0 – 100.0)
    completeness:  float = 0.0
    validity:      float = 0.0
    consistency:   float = 0.0
    uniqueness:    float = 0.0
    integrity:     float = 100.0   # 100 when no referential checks applied
    timeliness:    float = 100.0   # 100 when no date checks applied

    # Computed from dimensions
    overall_score: float = 0.0
    letter_grade:  str = "F"
    passed:        bool = False     # True when overall_score >= warning_threshold

    # Record funnel
    total_records:    int = 0
    valid_records:    int = 0
    invalid_records:  int = 0
    warning_records:  int = 0

    # Rule execution summary
    total_rules_executed: int = 0
    rules_passed:         int = 0
    rules_failed:         int = 0
    total_violations:     int = 0
    error_violations:     int = 0
    warning_violations:   int = 0

    def compute_overall(self) -> None:
        """
        Compute overall_score as a weighted average of dimensions.

        Weights reflect business importance:
          completeness  30% — missing data is the most common enterprise problem
          validity      35% — business rule compliance is the primary quality gate
          consistency   15% — format consistency affects downstream processing
          uniqueness    10% — duplicates are serious but less common
          integrity     5%  — referential checks may not apply to all datasets
          timeliness    5%
        """
        self.overall_score = round(
            self.completeness  * 0.30 +
            self.validity      * 0.35 +
            self.consistency   * 0.15 +
            self.uniqueness    * 0.10 +
            self.integrity     * 0.05 +
            self.timeliness    * 0.05,
            2,
        )
        self.letter_grade = self._to_letter_grade(self.overall_score)

    @staticmethod
    def _to_letter_grade(score: float) -> str:
        """Map score 0–100 to letter grade A+/A/B/C/D/F."""
        if score >= 97: return "A+"
        if score >= 90: return "A"
        if score >= 80: return "B"
        if score >= 70: return "C"
        if score >= 60: return "D"
        return "F"

    def to_dict(self) -> dict[str, Any]:
        return {
            "overall_score":         self.overall_score,
            "letter_grade":          self.letter_grade,
            "completeness":          round(self.completeness,  2),
            "validity":              round(self.validity,      2),
            "consistency":           round(self.consistency,   2),
            "uniqueness":            round(self.uniqueness,    2),
            "integrity":             round(self.integrity,     2),
            "timeliness":            round(self.timeliness,    2),
            "total_records":         self.total_records,
            "valid_records":         self.valid_records,
            "invalid_records":       self.invalid_records,
            "warning_records":       self.warning_records,
            "total_violations":      self.total_violations,
            "error_violations":      self.error_violations,
            "warning_violations":    self.warning_violations,
            "total_rules_executed":  self.total_rules_executed,
        }


# ---------------------------------------------------------------------------
# ValidationReport — full report for one validation run
# ---------------------------------------------------------------------------

@dataclass
class ValidationReport:
    """
    Complete validation output for one dataset.

    Contains every violation, column profile, and quality score.
    Serializes to JSON, CSV, or Excel for reports and audit storage.
    """

    # Identity
    report_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    pipeline_run_id: str | None = None
    ingestion_event_id: str | None = None
    dataset_type: str = ""
    original_filename: str = ""
    validated_at: datetime = field(default_factory=datetime.utcnow)

    # Timing
    duration_seconds: float = 0.0

    # Violations by severity
    violations: list[RuleViolation] = field(default_factory=list)

    # Column profiles
    column_profiles: dict[str, ColumnProfile] = field(default_factory=dict)

    # Quality score
    quality_score: QualityScore = field(default_factory=QualityScore)

    # Schema analysis
    missing_columns:    list[str] = field(default_factory=list)
    unexpected_columns: list[str] = field(default_factory=list)
    duplicate_columns:  list[str] = field(default_factory=list)

    # Row-level flags (row indices only — data is NOT copied here)
    invalid_row_indices:  set[int] = field(default_factory=set)
    warning_row_indices:  set[int] = field(default_factory=set)

    @property
    def error_violations(self) -> list[RuleViolation]:
        return [v for v in self.violations if v.severity == Severity.ERROR]

    @property
    def warning_violations(self) -> list[RuleViolation]:
        return [v for v in self.violations if v.severity == Severity.WARNING]

    @property
    def violation_count(self) -> int:
        return len(self.violations)

    @property
    def has_errors(self) -> bool:
        return bool(self.error_violations)

    def to_summary_dict(self) -> dict[str, Any]:
        """Compact summary suitable for API responses."""
        return {
            "report_id":          self.report_id,
            "dataset_type":       self.dataset_type,
            "original_filename":  self.original_filename,
            "validated_at":       self.validated_at.isoformat(),
            "duration_seconds":   round(self.duration_seconds, 3),
            "quality_score":      self.quality_score.to_dict(),
            "total_violations":   self.violation_count,
            "error_violations":   len(self.error_violations),
            "warning_violations": len(self.warning_violations),
            "missing_columns":    self.missing_columns,
            "unexpected_columns": self.unexpected_columns,
        }


# ---------------------------------------------------------------------------
# ValidationResult — top-level output to the pipeline engine
# ---------------------------------------------------------------------------

@dataclass
class ValidationResult:
    """
    The top-level output of the Validation Engine.

    Returned by ValidationEngine.validate() to the pipeline engine, which uses it to:
    1. Create the StageResult record for the validation stage
    2. Pass valid_df and rejected_df to the Cleaning Engine
    3. Persist the quality score to data_quality_scores table
    4. Decide whether to proceed (score above threshold) or abort

    CRITICAL: valid_df and rejected_df are VIEWS/SUBSETS of the original DataFrame.
    No data has been modified. They are produced by boolean-indexing the original.
    """

    success: bool
    dataset_type: str

    # DataFrame subsets (unmodified data — only row selection, no value changes)
    valid_df: pd.DataFrame = field(default_factory=pd.DataFrame)
    rejected_df: pd.DataFrame = field(default_factory=pd.DataFrame)
    warning_df: pd.DataFrame = field(default_factory=pd.DataFrame)

    # Full report
    report: ValidationReport = field(default_factory=ValidationReport)

    # Quick-access quality score
    quality_score: float = 0.0
    letter_grade: str = "F"
    passed_threshold: bool = False

    # Error information (set when success=False)
    error_message: str | None = None
    error_code: str | None = None

    # Timing
    duration_seconds: float = 0.0

    @property
    def valid_count(self) -> int:
        return len(self.valid_df)

    @property
    def rejected_count(self) -> int:
        return len(self.rejected_df)

    @property
    def warning_count(self) -> int:
        return len(self.warning_df)

    def __repr__(self) -> str:
        return (
            f"ValidationResult("
            f"success={self.success}, "
            f"score={self.quality_score:.1f} ({self.letter_grade}), "
            f"valid={self.valid_count}, "
            f"rejected={self.rejected_count}, "
            f"warnings={self.warning_count})"
        )
